sudo: false
language: node_js
node_js:
  - '4.2'
before_install:
  - "npm install -g grunt-cli"
install: npm install
env:
  - CXX=g++-4.8
  - ABLY_LOG_LEVEL=1
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

script:
  ./test/bin/ci-travis-all.sh
