language: node_js
node_js:
  - '4.2'
  - '0.12'
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "npm install -g grunt-cli"
install: npm install
addons:
  firefox: "31.0esr"
