sudo: false
dist: trusty
language: node_js
node_js:
  - '4.2'
before_install:
  - "npm install -g grunt-cli"
install: npm install
env:
  global:
    - ABLY_LOG_LEVEL=1
  matrix:
    - B0=test:nodeunit

script:
  ./test/bin/ci-travis-all.sh
