name: Publish to CDN
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version, without v prefix, appended to v to locate tag'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v2
        with:
          ref: v${{ github.event.inputs.version }}
      - name: Use Node.js 14.x
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SET_ACCESS_KEY }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - run: node scripts/cdn_deploy.js --tag=v${{ github.event.inputs.version }}
