on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-playwright:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
        matrix:
            browser: [chromium, firefox, webkit]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/
      - uses: microsoft/playwright-github-action@v1
      - run: npm ci
      - env:
          PLAYWRIGHT_BROWSER: ${{ matrix.browser }}
        run: npm run test:playwright
