on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-karma-firefox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - run: xvfb-run -a npm run test:karma
